spring:
  application:
    name: zkf-dispatch

server:
  port: 9006



grpc:
  client:
    grpc-server:
      address: 'discovery:///zim-server-ws'
      negotiation-type: plaintext
      enable-keep-alive: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: zkf-dispatch
    #    重试次数，加上第一次，共4次
    retry-times-when-send-failed: 3